spring.application.name=api-gateway
server.port=9000

# Actuator & Prometheus
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,prometheus
management.metrics.tags.application=${spring.application.name}

#Resilience 4j Properties
#This will enable resiliece4J data to the actuator endpoints
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
#ativa pelo numero de requests
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
#o numero de request que recebe (acredito que seja de um certo IP para ativar o state de open)
resilience4j.circuitbreaker.configs.default.slidingWindowSize=8
#percentagem... se 20% dos 8 requests acima falham o state open é ativo
resilience4j.circuitbreaker.configs.default.failureRateThreshold=20
#numero minimo de calls para que o circuit breaker seja ativo, caso falhem ou passem, dentro do mesmo window começa a analisar a partir de 4 requests
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=4
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
