spring.application.name=alert-service
server.port=8084


#Kafka - consumer
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=alert-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#the producer path and the consumer path
spring.kafka.consumer.properties.spring.json.trusted.packages=com.archielcode.kafka.event,com.archiecode.kafka.event
spring.kafka.consumer.properties.spring.json.type.mapping=com.archielcode.kafka.event.AlertingEvent:com.archiecode.kafka.event.AlertingEvent

spring.datasource.url=jdbc:postgresql://localhost:5432/home_energy_tracker
spring.datasource.username=postgres
spring.datasource.password=pgpwd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Mailpit SMTP Configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false