CREATE TABLE device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    type VARCHAR(50),
    location VARCHAR(255),
    user_id BIGINT,

    CONSTRAINT pk_device PRIMARY KEY (id),

    CONSTRAINT fk_device_user
        FOREIGN KEY (user_id)
        REFERENCES "usuario" (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_device_user_id
    ON device (user_id);