spring.application.name=insight-service
server.port=8085

usage.service.url=http://localhost:8083/api/v1/usage

#this model deep-seek coder does not work for general prompts I believe that this one is just for coding purposes
#spring.ai.ollama.chat.options.model=deepseek-coder
spring.ai.ollama.init.pull-model-strategy=never

spring.ai.ollama.chat.options.model=mistral
