spring.application.name=usage-service
server.port=8083

#Kafka - consumer
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=usage-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.type.mapping=energyUsageEvent:com.archielcode.kafka.event.EnergyUsageEvent

# Allow Spring Kafka to trust the legacy package from previously produced messages
spring.kafka.consumer.properties.spring.json.trusted.packages=com.archielcode.kafka.event,com.archiecode.kafka.event

# Map the legacy package to your current class path
spring.kafka.consumer.properties.spring.json.type.mapping=com.archiecode.kafka.event.EnergyUsageEvent:com.archielcode.kafka.event.EnergyUsageEvent

#Influx DB Configuration
influx.url=http://localhost:8072
influx.token=my-token
influx.org=archiecode
influx.bucket=usage-bucket